spring.application.name=dealersautocenter

spring.profiles.active=dev


spring.datasource.url=jdbc:mysql://localhost:3306/dealersautocenter_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=root

## JPA Hibernate Properties
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
